<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="c:\program files (x86)\microsoft visual studio 14.0\team tools\static analysis tools\fxcop\Xml\CodeAnalysisReport.xsl"?>
<FxCopReport Version="14.0">
 <Targets>
  <Target Name="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test\bin\Debug\Project.MSH.Test.dll">
   <Modules>
    <Module Name="project.msh.test.dll">
     <Namespaces>
      <Namespace Name="Project.MSH.Test">
       <Types>
        <Type Name="PessoaTest" Kind="Class" Accessibility="Public" ExternallyVisible="True">
         <Members>
          <Member Name="#should_delete_person_by_id()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="149">'PessoaTest.should_delete_person_by_id()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#should_get_person_by_id()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="70">'PessoaTest.should_get_person_by_id()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#should_insert_new_person()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="122">'PessoaTest.should_insert_new_person()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#should_inserts_generic_name_on_database()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="208">'PessoaTest.should_inserts_generic_name_on_database()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="212">'PessoaTest.should_inserts_generic_name_on_database()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#should_inserts_generic_name_on_database_others()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="289">'PessoaTest.should_inserts_generic_name_on_database_others()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="293">'PessoaTest.should_inserts_generic_name_on_database_others()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#should_select_all_people()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="45">'PessoaTest.should_select_all_people()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#should_select_all_people_with_birth_date_above()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="95">'PessoaTest.should_select_all_people_with_birth_date_above()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#should_update_person_surname()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="PessoaTest.cs" Line="180">'PessoaTest.should_update_person_surname()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
         </Members>
        </Type>
        <Type Name="UnitTest1" Kind="Class" Accessibility="Public" ExternallyVisible="True">
         <Members>
          <Member Name="#deveria_trazer_pessoas()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="UnitTest1.cs" Line="66">'UnitTest1.deveria_trazer_pessoas()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#should_connect_with_database()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2016-06-09 04:42:32Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\_Brum\_git\mhs\project\Project.MSH\Project.MSH.Test" File="UnitTest1.cs" Line="36">'UnitTest1.should_connect_with_database()' rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Issue>
            </Message>
           </Messages>
          </Member>
         </Members>
        </Type>
       </Types>
      </Namespace>
     </Namespaces>
    </Module>
   </Modules>
  </Target>
 </Targets>
 <Rules>
  <Rule TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200">
   <Name>Rethrow to preserve stack details</Name>
   <Description>Use the IL rethrow instruction to preserve original stack details when re-raising a caught exception.</Description>
   <Resolution Name="Default">{0} rethrows a caught exception and specifies it explicitly as an argument. Use 'throw' without an argument instead, in order to preserve the stack location where the exception was initially raised.</Resolution>
   <Owner />
   <Url>http://msdn.microsoft.com/library/ms182363.aspx</Url>
   <Email>[none]</Email>
   <MessageLevel Certainty="95">Error</MessageLevel>
   <File Name="usagerules.dll" Version="14.0.0.0" />
  </Rule>
 </Rules>
 <Localized>
  <String Key="Category">Category</String>
  <String Key="Certainty">Certainty</String>
  <String Key="CollapseAll">Collapse All</String>
  <String Key="CheckId">Check Id</String>
  <String Key="Error">Error</String>
  <String Key="Errors">error(s)</String>
  <String Key="ExpandAll">Expand All</String>
  <String Key="Help">Help</String>
  <String Key="Line">Line</String>
  <String Key="Messages">message(s)</String>
  <String Key="LocationNotStoredInPdb">[Location not stored in Pdb]</String>
  <String Key="Project">Project</String>
  <String Key="Resolution">Resolution</String>
  <String Key="Rule">Rule</String>
  <String Key="RuleFile">Rule File</String>
  <String Key="RuleDescription">Rule Description</String>
  <String Key="Source">Source</String>
  <String Key="Status">Status</String>
  <String Key="Target">Target</String>
  <String Key="Warning">Warning</String>
  <String Key="Warnings">warning(s)</String>
  <String Key="ReportTitle">Code Analysis Report</String>
 </Localized>
</FxCopReport>
